### ISSUE TITLE
Probably a wrong error when master is unreachable

### ISSUE THREAD

**Issue by Gerold103** [tarantool/vshard#181]
```YAML
localhost:3301> vshard.router.callrw(1, 'tostring', {1}, {timeout=1})
---
- null
- type: ClientError
  code: 77
  message: Invalid argument
  trace:
  - file: builtin/box/net_box.lua
    line: 781
...
```

**Comment by Gerold103** [comment]
Can't reproduce.
```YAML
  - ['UNREACHABLE_MASTER', 'Master of replicaset ac522f65-aa94-4134-9f64-51ee384f1a54
      is unreachable: disconnected']
  - ['SUBOPTIMAL_REPLICA', 'A current read replica in replicaset ac522f65-aa94-4134-9f64-51ee384f1a54
      is not optimal']
  - ['UNREACHABLE_MASTER', 'Master of replicaset cbf06940-0790-498b-948d-042b62cf3d29
      is unreachable: disconnected']
  - ['SUBOPTIMAL_REPLICA', 'A current read replica in replicaset cbf06940-0790-498b-948d-042b62cf3d29
      is not optimal']
...

unix/:./data/router_1.control> vshard.router.callrw(1, 'tostring', {1}, {timeout=1})
---
- null
- type: ClientError
  code: 77
  message: Connection refused
  trace:
  - file: builtin/box/net_box.lua
    line: 490
...
```

**Comment by bofm** [comment]
Test case:

https://gist.github.com/bofm/c7da0a1b57267ea151a32cdd0548b23d

**Comment by Gerold103** [comment]
Still can't reproduce, sorry. I've tried it, but still "Connection refused".

**Comment by bofm** [comment]
What OS did you use?

**Comment by Gerold103** [comment]
MacOSX Mojave

**Comment by bofm** [comment]
A test run on MacOS, docker for mac 2.0.0.3 on my MBP15'18

```
$ curl -L https://gist.github.com/bofm/c7da0a1b57267ea151a32cdd0548b23d/archive/72b27f3220f756a651fa21ce4be0f19fd3e27c56.zip -o test.zip && unzip test.zip && cd c* && docker-compose up router
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   176    0   176    0     0    329      0 --:--:-- --:--:-- --:--:--   329
100  2636    0  2636    0     0   2143      0 --:--:--  0:00:01 --:--:--  2143
Archive:  test.zip
72b27f3220f756a651fa21ce4be0f19fd3e27c56
   creating: c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56/
  inflating: c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56/Dockerfile
  inflating: c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56/app.lua
  inflating: c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56/docker-compose.yml
Creating c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56_t1_1 ... done
Creating c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56_t3_1 ... done
Creating c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56_t2_1 ... done
Creating c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56_t4_1 ... done
Creating c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56_router_1 ... done
Attaching to c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56_router_1
router_1  | Starting router configuration
router_1  | Calling box.cfg()...
router_1  | {"listen":"0.0.0.0:3301"}
router_1  | 2019-05-21 17:37:44.889 [1] main/101/interactive C> Tarantool 1.10.2-203-g0b7078a93
router_1  | 2019-05-21 17:37:44.889 [1] main/101/interactive C> log level 5
router_1  | 2019-05-21 17:37:44.890 [1] main/101/interactive I> mapping 268435456 bytes for memtx tuple arena...
router_1  | 2019-05-21 17:37:44.890 [1] main/101/interactive I> mapping 134217728 bytes for vinyl tuple arena...
router_1  | 2019-05-21 17:37:44.891 [1] main/101/interactive I> instance uuid fe1b0740-5878-450e-9446-aaa98d851445
router_1  | 2019-05-21 17:37:44.891 [1] iproto/101/main I> binary: bound to 0.0.0.0:3301
router_1  | 2019-05-21 17:37:44.891 [1] main/101/interactive I> initializing an empty data directory
router_1  | 2019-05-21 17:37:44.897 [1] main/101/interactive I> assigned id 1 to replica fe1b0740-5878-450e-9446-aaa98d851445
router_1  | 2019-05-21 17:37:44.897 [1] main/101/interactive I> cluster uuid adafaffc-2dd8-4f56-bedc-ba5165af2e46
router_1  | 2019-05-21 17:37:44.898 [1] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
router_1  | 2019-05-21 17:37:44.900 [1] snapshot/101/main I> done
router_1  | 2019-05-21 17:37:44.901 [1] main/101/interactive I> ready to accept requests
router_1  | 2019-05-21 17:37:44.901 [1] main/107/checkpoint_daemon I> started
router_1  | 2019-05-21 17:37:44.901 [1] main/107/checkpoint_daemon I> scheduled the next snapshot at Tue May 21 19:23:18 2019
router_1  | 2019-05-21 17:37:44.901 [1] main/101/interactive I> Box has been configured
router_1  | 2019-05-21 17:37:44.905 [1] main/112/t1:3301 (net.box) net_box.lua:904 W> t1:3301: Instance bootstrap hasn't finished yet
router_1  | 2019-05-21 17:37:44.905 [1] main/113/t2:3301 (net.box) net_box.lua:904 W> t2:3301: Instance bootstrap hasn't finished yet
router_1  | 2019-05-21 17:37:44.905 [1] main/115/t4:3301 (net.box) net_box.lua:904 W> t4:3301: Instance bootstrap hasn't finished yet
router_1  | 2019-05-21 17:37:44.906 [1] main/114/t3:3301 (net.box) I> connected to t3:3301
router_1  | 2019-05-21 17:37:45.402 [1] main/116/lua I> failover_f has been started
router_1  | 2019-05-21 17:37:45.402 [1] main/116/lua I> New replica t3(storage@t3:3301) for replicaset(uuid="bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb", master=t3(storage@t3:3301))
router_1  | 2019-05-21 17:37:45.402 [1] main/116/lua I> All replicas are ok
router_1  | 2019-05-21 17:37:45.402 [1] main/116/lua I> Failovering step is finished. Schedule next after 1.000000 seconds
router_1  | 2019-05-21 17:37:45.402 [1] main/117/lua I> discovery_f has been started
router_1  | 2019-05-21 17:37:45.408 [1] main/112/t1:3301 (net.box) I> connected to t1:3301
router_1  | 2019-05-21 17:37:45.408 [1] main/115/t4:3301 (net.box) I> connected to t4:3301
router_1  | 2019-05-21 17:37:45.409 [1] main/113/t2:3301 (net.box) I> connected to t2:3301
router_1  | 2019-05-21 17:37:46.403 [1] main/116/vshard.failover._static_router I> New replica t1(storage@t1:3301) for replicaset(uuid="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa", master=t1(storage@t1:3301))
router_1  | 2019-05-21 17:37:46.403 [1] main/116/vshard.failover._static_router I> All replicas are ok
router_1  | 2019-05-21 17:37:46.403 [1] main/116/vshard.failover._static_router I> Failovering step is finished. Schedule next after 1.000000 seconds
router_1  | 2019-05-21 17:37:46.430 [1] main/101/interactive I> Buckets from 1 to 5000 are bootstrapped on "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
router_1  | 2019-05-21 17:37:46.455 [1] main/101/interactive I> Buckets from 5001 to 10000 are bootstrapped on "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"
router_1  | 2019-05-21 17:37:47.405 [1] main/116/vshard.failover._static_router I> All replicas are ok
router_1  | 2019-05-21 17:37:55.413 [1] main/117/vshard.discovery._static_router I> Updated replicaset(uuid="bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb", master=t3(storage@t3:3301)) buckets: was 0, became 5000
router_1  | 2019-05-21 17:38:05.418 [1] main/117/vshard.discovery._static_router I> Updated replicaset(uuid="aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa", master=t1(storage@t1:3301)) buckets: was 0, became 5000
router_1  | 2019-05-21 17:38:05.575 [1] main/112/t1:3301 (net.box) I> disconnected from t1:3301
router_1  | 2019-05-21 17:38:05.575 [1] main/112/t1:3301 (net.box) net_box.lua:904 W> t1:3301: Peer closed
router_1  | 2019-05-21 17:38:05.575 [1] main/101/interactive replicaset.lua:244 E> Exception during calling 'vshard.storage.call' on 't1(storage@t1:3301)': Peer closed
router_1  | 2019-05-21 17:38:06.089 [1] main/112/t1:3301 (net.box) net_box.lua:904 W> t1:3301: Invalid argument
router_1  | 2019-05-21 17:38:06.575 [1] main/101/interactive replicaset.lua:244 E> Exception during calling 'vshard.storage.call' on 't1(storage@t1:3301)': Invalid argument
router_1  | 2019-05-21 17:38:06.576 [1] main/101/interactive (command line):24 E> ---
router_1  | err:
router_1  |   type: ClientError
router_1  |   code: 77
router_1  |   message: Invalid argument
router_1  |   trace:
router_1  |   - file: builtin/box/net_box.lua
router_1  |     line: 486
router_1  | ...
router_1  |
c7da0a1b57267ea151a32cdd0548b23d-72b27f3220f756a651fa21ce4be0f19fd3e27c56_router_1 exited with code 1
```

**Comment by Gerold103** [comment]
Still does not work. I've discovered, that such an error could be returned from libc socket API only, as an errno, which is used in socket.lua module. Can't find where exactly.

**Comment by Gerold103** [comment]
Can you use a custom Tarantool build from a branch? I want to check something.

**Comment by bofm** [comment]
Tried on my colleague's computer and it worked.

**Comment by bofm** [comment]
Can I increase verbosity or turn something on to show more info? Please give me instructions.

**Comment by bofm** [comment]
Can it be related to the stdout tty type? I used iTerm2. Just in case...

**Comment by Gerold103** [comment]
Log level will not help here. Can you try a custom build of Tarantool from a branch?

**Comment by Gerold103** [comment]
Or I could build it for you, since I use Mac too. Anyway, I need to add more logging. I am 90% sure it is socket.lua module fault - it makes lots of EINVAL errno settings, and I even reproduced some of them locally. To be 100% sure I need to add more logs.

**Comment by bofm** [comment]
> Can you try a custom build 

Yes

**Comment by bofm** [comment]
Probably related. `vshard.router.sync` ignores the timeout when one of the master instances is down.

Here I killed `t3` from the test case setup.

```yaml
localhost:3301> do local t = os.time(); local r1, r2 = vshard.router.sync(1); return r1, r2, os.time() - t end
---
- null
- replicaset: bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
  code: 77
  trace:
  - file: builtin/box/net_box.lua
    line: 488
  type: ClientError
  message: Invalid argument
- 64
...
```
