### ISSUE TITLE
Track replication upstream.idle when calling on replica 

### ISSUE THREAD

**Issue by grafin** [tarantool/vshard#453]
Currently any read call, routed to replica will be executed not regarding if the replica is connected to any other instance. In my case:
1) Have a shard with 3 instances, one (A) being master (`box.info.ro == false`) others (B) and (C) being replicas (`box.info.ro == true`)
2) For some unrelated to vshard reason all appliers on replica (B) broke down not being able to recover without manual instance restart. All `box.info.replication[n].upstream.status` are `disconnected`. (n. don't use DML in triggers on ro instances, if the row is received via applier)
3) All reads, routed to replica (B) returned very old data (instance (B) was broken for several hours).

We could prevent such dirty reads, using available data, as stated in our docs:
> Therefore, in a healthy replication setup, idle should never exceed replication_timeout: if it does, either the replication is lagging seriously behind, because the master is running ahead of the replica, or the network link between the instances is down.

It would be great if we could prevent those dirty reads by not routing any request to replicas (ro instances) which are disconnected from everyone, or maybe even give the ability to configure some `max_replication_idle` or `max_replication_lag` and return errors when trying to process a request on replica whose current `max(replication[n].upstream.idle/lag)` exceeds configured value.

**Comment by sergepetrenko** [comment]
> Can't we lean just on box.info.status?

I assume you meant `upstream.status`?
Still, no. `upstream.status` may be 'follow' but the replica still may have a huge lag to this upstream. For example, when master performs a batch of changes, which replica can't apply as fast as master did.

**Comment by grafin** [comment]
During fixing the initial problem i get the following upstream info in my case:
```
id: 1
    uuid: bbbbbbbb-bbbb-4000-b000-000000000001
    lsn: 60719
    upstream:
      peer: admin@localhost:48809
      lag: 0.0002281665802002
      status: stopped
      idle: 169.65149075794
      message: Can't modify data on a read-only instance - box.cfg.read_only is true
```
So monitoring `upstream.lag` doesn't solve the issue, and as @sergepetrenko mentioned `upstream.status` is not very effective too. Looks like it is best to check `upstream.idle`.
