### ISSUE TITLE
log: 'deploying exports' message has no core version

### ISSUE THREAD

**Issue by Totktonada** [tarantool/vshard#465]
Let's look on the code.

https://github.com/tarantool/vshard/blob/5bfe03b48839863c7a0098d27dbbee1d54890562/vshard/storage/exports.lua#L44-L48

https://github.com/tarantool/vshard/blob/5bfe03b48839863c7a0098d27dbbee1d54890562/vshard/storage/exports.lua#L59-L60

The `exports.core_version` field is always an empty string.

```yaml
# tarantool> lvutil = require('vshard.util')
# tarantool> lvutil.core_version
---
- id_middle: 1
  rel_type: entrypoint
  id_minor: 0
  id_major: 3
  id_commit: 9
  rel_num: 0
...
# tarantool> table.concat(lvutil.core_version, '.')
---
-
...
```

`table.concat()` concetenates an array, but not a map.
