### ISSUE TITLE
Garbage collector doesn't work with varbinary primary index

### ISSUE THREAD

**Issue by lowitea** [tarantool/vshard#507]
## Environment

Tarantool: 2.11.2
Vshard: 0.1.28

Space:

```
---yaml
- engine: memtx
  before_replace: 'function: 0x42739a18'
  field_count: 0
  is_sync: false
  is_local: false
  on_replace: 'function: 0x427399f0'
  temporary: false
  index:
    0: &0
      unique: true
      parts:
      - type: varbinary
        is_nullable: false
        fieldno: 2
      - type: varbinary
        is_nullable: false
        fieldno: 3
      hint: true
      id: 0
      type: TREE
      space_id: 516
      name: primary
    1: &1
      unique: false
      parts:
      - type: unsigned
        is_nullable: false
        fieldno: 1
      hint: true
      id: 1
      type: TREE
      space_id: 516
      name: bucket_id
    bucket_id: *1
    primary: *0
  type: normal
  enabled: true
  name: test_space
  id: 516
...
```

## Description

If I trigger a rebalance on the space with a primary key with varbinary fields, the buckets will be moved to new replicasets. However, they will not be deleted from the old ones.

## Logs

```
cluster.storage-1-1 | 2024-12-25 17:39:36.396 [188438] main/126/vshard.rebalancer/default I> Some buckets are not active, retry rebalancing later
cluster.storage-1-1 | 2024-12-25 17:39:39.731 [188438] main/124/vshard.gc/default init.lua:2244 E> Error during garbage collection step: Supplied key type of part 0 does not match index part type: expected varbinary
```
