### ISSUE TITLE
Remove passwords from router.info()/storage.info() and logs

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/vshard#53]
Password should be removed from all uris:

```
unix/:./data/router_1.control> vshard.router.info()
---
- replicasets:
    ac522f65-aa94-4134-9f64-51ee384f1a54:
      replica:
        status: available
        uri: storage:storage@127.0.0.1:3303
        uuid: 1e02ae8a-afc0-4e91-ba34-843a356b8ed7
      uuid: ac522f65-aa94-4134-9f64-51ee384f1a54
      master:
        status: available
        uri: storage:storage@127.0.0.1:3303
        uuid: 1e02ae8a-afc0-4e91-ba34-843a356b8ed7
    cbf06940-0790-498b-948d-042b62cf3d29:
      replica:
        status: available
        uri: storage:storage@127.0.0.1:3301
        uuid: 8a274925-a26d-47fc-9e1b-af88ce939412
      uuid: cbf06940-0790-498b-948d-042b62cf3d29
      master:
        status: available
        uri: storage:storage@127.0.0.1:3301
        uuid: 8a274925-a26d-47fc-9e1b-af88ce939412
  status: 0
  alerts: []
```
